apiVersion: v1
kind: Ingress
metadata:
  name: rgb-lightness-server
  namespace: rgb-lightness-server
spec:
  rules:
    - host: rgb-lightness.771.blue
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rgb-lightness-server
                port:
                  name: web
