apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-config
  namespace: kube-system
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: cluster-infra
  source:
    path: _infrastructure/k3s/traefik
    repoURL: https://github.com/jemand771/server-deployments.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
